CLASSE               TOKEN           LIN COL
---------------------------------------------
PALAVRA_RESERVADA    int                1    1
INDICADOR            x                  1    5
NUMERAL              5                  1    9
SEPARADOR            ;                  1   10
PALAVRA_RESERVADA    int                2    1
INDICADOR            z                  2    5
NUMERAL              0                  2    9
SEPARADOR            ;                  2   10
PALAVRA_RESERVADA    int                4    1
INDICADOR            num                4    5
SEPARADOR            (                  4    8
INDICADOR            x                  4    9
SEPARADOR            )                  4   10
SEPARADOR            {                  4   11
INDICADOR            printf             6    5
SEPARADOR            (                  6   11
LITERAL              O numero é: %d\n    6   12
SEPARADOR            ,                  6   30
INDICADOR            x                  6   32
SEPARADOR            )                  6   33
SEPARADOR            ;                  6   34
PALAVRA_RESERVADA    while              7    1
SEPARADOR            (                  7    6
INDICADOR            x                  7    7
NUMERAL              0                  7    9
SEPARADOR            )                  7   10
SEPARADOR            {                  7   11
INDICADOR            x                  8    5
SEPARADOR            ;                  8    8
SEPARADOR            }                 11    1
PALAVRA_RESERVADA    int               12    1
INDICADOR            main              12    5
SEPARADOR            (                 12    9
SEPARADOR            )                 12   10
SEPARADOR            {                 12   12
INDICADOR            z                 13    5
INDICADOR            x                 13    9
NUMERAL              10                13   13
SEPARADOR            ;                 13   15
PALAVRA_RESERVADA    return            14    5
NUMERAL              0                 14   12
SEPARADOR            ;                 14   13
SEPARADOR            }                 15    1
COMENTARIO           eae tranquilo     15    2
INDICADOR            sdsaweew          16    1
