CLASSE               TOKEN           LIN COL
---------------------------------------------
INDICADOR            #                  1    1
INDICADOR            include            1    2
OPERADOR             <                  1   10
INDICADOR            stdio              1   11
ERRO_LEXICO          .                  1   16
INDICADOR            h                  1   17
OPERADOR             >                  1   18
INDICADOR            #                  2    1
INDICADOR            include            2    2
OPERADOR             <                  2   10
INDICADOR            ctype              2   11
ERRO_LEXICO          .                  2   16
INDICADOR            h                  2   17
OPERADOR             >                  2   18
INDICADOR            #                  3    1
INDICADOR            include            3    2
OPERADOR             <                  3   10
INDICADOR            regex              3   11
ERRO_LEXICO          .                  3   16
INDICADOR            h                  3   17
OPERADOR             >                  3   18
INDICADOR            #                  4    1
INDICADOR            include            4    2
OPERADOR             <                  4   10
INDICADOR            string             4   11
ERRO_LEXICO          .                  4   17
INDICADOR            h                  4   18
OPERADOR             >                  4   19
PALAVRA_RESERVADA    int                8    1
INDICADOR            x                  8    5
OPERADOR             =                  8    7
NUMERAL              5                  8    9
SEPARADOR            ;                  8   10
PALAVRA_RESERVADA    int                9    1
INDICADOR            z                  9    5
OPERADOR             =                  9    7
NUMERAL              0                  9    9
SEPARADOR            ;                  9   10
PALAVRA_RESERVADA    int               11    1
INDICADOR            num               11    5
SEPARADOR            (                 11    8
INDICADOR            x                 11    9
SEPARADOR            )                 11   10
SEPARADOR            {                 11   11
INDICADOR            printf            13    5
SEPARADOR            (                 13   11
LITERAL              O numero é: %d\n   13   12
SEPARADOR            ,                 13   30
INDICADOR            x                 13   32
SEPARADOR            )                 13   33
SEPARADOR            ;                 13   34
PALAVRA_RESERVADA    while             14    1
SEPARADOR            (                 14    6
INDICADOR            x                 14    7
OPERADOR             >                 14    8
NUMERAL              0                 14    9
SEPARADOR            )                 14   10
SEPARADOR            {                 14   11
INDICADOR            x                 15    5
OPERADOR             -                 15    6
OPERADOR             -                 15    7
SEPARADOR            ;                 15    8
SEPARADOR            }                 18    1
PALAVRA_RESERVADA    int               19    1
INDICADOR            main              19    5
SEPARADOR            (                 19    9
SEPARADOR            )                 19   10
SEPARADOR            {                 19   12
INDICADOR            z                 20    5
OPERADOR             =                 20    7
INDICADOR            x                 20    9
OPERADOR             +                 20   11
NUMERAL              10                20   13
SEPARADOR            ;                 20   15
PALAVRA_RESERVADA    return            21    5
NUMERAL              0                 21   12
SEPARADOR            ;                 21   13
SEPARADOR            }                 22    1
COMENTARIO           big gib           22    2
NUMERAL              0                 23    1
ERRO_LEXICO          .                 23    2
NUMERAL              0                 23    3
ERRO_LEXICO          .                 23    4
NUMERAL              0                 23    5
ERRO_LEXICO          .                 23    6
NUMERAL              33                23    7
INDICADOR            @                 23    9
OPERADOR             =                 23   11
NUMERAL              5                 23   13
OPERADOR             -                 23   15
OPERADOR             -                 23   16
NUMERAL              4                 23   18
NUMERAL              0                 23   20
OPERADOR             +                 23   21
OPERADOR             /                 24    1
OPERADOR             *                 24    2
INDICADOR            freez             25    1
OPERADOR             *                 26    1
OPERADOR             /                 26    2
INDICADOR            sdsaweew          27    1
