CLASSE               TOKEN           LIN COL
---------------------------------------------
PALAVRA_RESERVADA    #include           1    1
INDICADOR            <stdio.h>          1    9
PALAVRA_RESERVADA    int                3    1
INDICADOR            main               3    5
SEPARADOR            (                  3    9
SEPARADOR            )                  3   10
SEPARADOR            {                  3   12
PALAVRA_RESERVADA    int                5    5
INDICADOR            idade              5    9
SEPARADOR            ;                  5   14
PALAVRA_RESERVADA    char               6    5
INDICADOR            nome               6   10
SEPARADOR            [                  6   14
NUMERAL              50                 6   15
SEPARADOR            ]                  6   18
SEPARADOR            ;                  6   19
PALAVRA_RESERVADA    printf             9    5
SEPARADOR            (                  9   11
LITERAL              Digite seu nome:     9   12
SEPARADOR            )                  9   30
SEPARADOR            ;                  9   31
PALAVRA_RESERVADA    scanf             10    5
SEPARADOR            (                 10   10
LITERAL              %49s              10   11
SEPARADOR            ,                 10   16
INDICADOR            nome              10   18
SEPARADOR            )                 10   22
SEPARADOR            ;                 10   23
PALAVRA_RESERVADA    printf            12    5
SEPARADOR            (                 12   11
LITERAL              Digite sua idade:    12   12
SEPARADOR            )                 12   31
SEPARADOR            ;                 12   32
PALAVRA_RESERVADA    scanf             13    5
SEPARADOR            (                 13   10
LITERAL              %d                13   11
SEPARADOR            ,                 13   14
ERRO_LEXICO          &                 13   16
INDICADOR            idade             13   17
SEPARADOR            )                 13   22
SEPARADOR            ;                 13   23
PALAVRA_RESERVADA    if                16    5
SEPARADOR            (                 16    8
INDICADOR            idade             16    9
OPERADOR             >                 16   15
OPERADOR             =                 16   16
NUMERAL              18                16   18
SEPARADOR            )                 16   21
SEPARADOR            {                 16   23
PALAVRA_RESERVADA    printf            17    9
SEPARADOR            (                 17   15
LITERAL              Olá %s, você é maior de idade!\n   17   16
SEPARADOR            ,                 17   52
INDICADOR            nome              17   54
SEPARADOR            )                 17   58
SEPARADOR            ;                 17   59
SEPARADOR            }                 18    5
PALAVRA_RESERVADA    else              18    7
SEPARADOR            {                 18   12
PALAVRA_RESERVADA    printf            19    9
SEPARADOR            (                 19   15
LITERAL              Olá %s, você é menor de idade!\n   19   16
SEPARADOR            ,                 19   52
INDICADOR            nome              19   54
SEPARADOR            )                 19   58
SEPARADOR            ;                 19   59
SEPARADOR            }                 20    5
PALAVRA_RESERVADA    printf            23    5
SEPARADOR            (                 23   11
LITERAL              Contando até 5:\n   23   12
SEPARADOR            )                 23   31
SEPARADOR            ;                 23   32
PALAVRA_RESERVADA    for               24    5
SEPARADOR            (                 24    9
PALAVRA_RESERVADA    int               24   10
INDICADOR            i                 24   14
OPERADOR             =                 24   16
NUMERAL              1                 24   18
SEPARADOR            ;                 24   20
INDICADOR            i                 24   22
OPERADOR             <                 24   24
OPERADOR             =                 24   25
NUMERAL              5                 24   27
SEPARADOR            ;                 24   29
INDICADOR            i                 24   31
OPERADOR             +                 24   32
OPERADOR             +                 24   33
SEPARADOR            )                 24   34
SEPARADOR            {                 24   36
PALAVRA_RESERVADA    printf            25    9
SEPARADOR            (                 25   15
LITERAL              %d                25   16
SEPARADOR            ,                 25   20
INDICADOR            i                 25   22
SEPARADOR            )                 25   23
SEPARADOR            ;                 25   24
SEPARADOR            }                 26    5
PALAVRA_RESERVADA    printf            27    5
SEPARADOR            (                 27   11
LITERAL              \n                27   12
SEPARADOR            )                 27   15
SEPARADOR            ;                 27   16
PALAVRA_RESERVADA    return            29    5
NUMERAL              0                 29   12
SEPARADOR            ;                 29   14
SEPARADOR            }                 30    1
